### ISSUE TITLE
Broken icons and console warnings

### ISSUE THREAD

**Issue by rwest202** [wesbos/Syntax#12]
Hi,

Noticed some broken icons on this page. Image below.
https://syntax.fm/show/001/react-tools

![screenshot-syntax fm-2017-07-07-13-18-37](https://user-images.githubusercontent.com/7718824/27944095-fa94bcaa-62a9-11e7-9913-056fca881200.png)

Also some console errors

`/Mixed Content: The page at 'https://syntax.fm/?__s=mvrzvydym18bsfdsyedw' was loaded over HTTPS, but requested an insecure favicon 'http://syntax.fm/static/favicon.png'. This content should also be served over HTTPS.
app.js:8 Setting current playing`

**Comment by atgg** [comment]
Hi there, seems like your browser does not support emojis. The site uses emojis as icons instead of something like Font Awesome.

**Comment by ink8bit** [comment]
@atgg You are right about icons but the issue (mentioned above) is about `http` in the favicon path.

@wesbos @stolinski Please, check `IndexPage` component and its `prop` - `baseURL`. It contains `http`. 
I assume the line `app.js:8 Setting current playing` exists because of forgotten `console.log` statement.

**Comment by atgg** [comment]
@ink8bit From what I read from the title, the issue is both about the "broken" icons and the favicon.

The protocol is not hardcoded into the `baseURL` prop. Instead, it extracts the protcol from the request header. ([Code](https://github.com/wesbos/Syntax/blob/42a5a3313240b49fa34950194dab5d1bf9bc66c5/pages/index.js#L23))

Also, I have removed the redundant `console.log` from `<IndexPage />` as a part of my pull request (#8).

**Comment by ink8bit** [comment]
@atgg Oh, thanks. Now I see. Btw, you've done a huge work with this `PR`!
