### ISSUE TITLE
Query param issue

### ISSUE THREAD

**Issue by mskwio** [wesbos/Syntax#528]
Hey,
I've recently discovered one bug related to query param redirection. When we go to https://syntax.fm/?abc, app crashes (An unexpected error has occurred). It's a rather big problem because some websites (Facebook for example), are adding their own query param when someone clicks a link on their website.

The reason is, in the next.config.js there is a "rewrites" function that for the root URL ("/") returns the component under the "/show/latest/latest" URL. "/?abc", unfortunately, is not interpreted as "/" so the app tries to find the show, it can't so, as a result, it throws the error.

One, simple solution would be to check if a show exists, if no, redirect to the root URL.
```
if (!show) {
  router.push('/');
  return null;
}
```
I suppose there is a lot better solution (maybe related to Next.js redirects feature).

**Comment by hangindev** [comment]
I believe the root cause is that `latest` show number is not handled properly on the client-side. The query param triggers a re-render on the client-side but the app doesn't understand `latest` as a show number. See [these lines](https://github.com/wesbos/Syntax/blob/40a7df3f29c4bf7682c359914cc20ef3b23dc214/pages/show/%5Bnumber%5D/%5Bslug%5D.js#L69-L74).

There is another way to break the app:

1. Visit [https://syntax.fm/show/latest/latest](https://syntax.fm/show/latest/latest)
2. Click a show (not the latest one)
3. Click the back button of your browser

I create a PR that would solve this issue #541.

**Comment by wesbos** [comment]
thanks! all fixed
