### ISSUE TITLE
Add favicon to sponsors page.

### ISSUE THREAD

**Issue by dzsi1994** [wesbos/Syntax#92]
Currently the favicon is missing if a user navigates to the sponsors page.
https://syntax.fm/sponsor

**Comment by jaredcaraway** [comment]
[Current meta component](https://github.com/wesbos/Syntax/blob/master/components/meta.js) appears to be designed specifically for the "shows" page - it reads the currently playing episode and plugs that info into the various meta tag attributes:

```
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta charSet="utf-8" />
      <meta property="og:audio" content={show.url} />
      <meta property="og:audio:secure_url" content={show.url} />
      <meta property="og:audio:type" content="audio/mp3" />
      <meta property="og:type" content="music.song" />
      <meta property="og:title" content={`${show.title} — Syntax Podcast ${show.displayNumber}`} />
      <meta
        property="og:description"
        content="Full Stack Developers Wes Bos and Scott Tolinski dive deep into web development topics, explaining how they work and talking about their own experiences. They cover from JavaScript frameworks like React, to the latest advancements in CSS to simplifying web tooling."
      />
      <meta property="og:url" content={`${baseURL}/show/${show.displayNumber}/${slug(show.title)}`} />
      <meta property="og:image" content={`${baseURL}/static/syntax-banner.png`} />
      <link rel="shortcut icon" href={`${baseURL}/static/favicon.png`} />
      <title>
        {show.title} — Syntax Podcast {show.displayNumber}
      </title>
      <style dangerouslySetInnerHTML={{ __html: stylesheet.replace(/\n/g, '') }} />
```
I wonder if this code could be easily adapted to detect if it's being loaded into the sponsor page or if it warrants its own meta component (or if the meta information should simply be hard-coded in, since it is not dynamic as it is for the shows page).

**Comment by brooksbecton** [comment]
I took a crack at this here: https://github.com/wesbos/Syntax/compare/master...brooksbecton:bug/sponsorMetaInfo

I had to be a little hacky because the conditional wanted one parent component, but I wasn't too sure on how to wrap meta tags. 

Also, this assumes the the page title matches path of the page component (which I think is ok because NextJS, but this is my first time messing with it), but I'm not sure how embedded pages would work in the future with this approach.

**Comment by papascott** [comment]
This being Hacktober I decided to take a look at this. I pretty much used @brooksbecton's changes, except I used a fragment to wrap the meta tags and calculated the baseURL prop on the sponsor page rather than hard coding the value. Passing the page title as show.title is a little wonky, but probably OK as long as there's only one page other than index.
